### ISSUE TITLE
code: concurrent and channel issue

### ISSUE THREAD

**Issue by vecio** [koding/websocketproxy#5]
https://github.com/koding/websocketproxy/blob/master/websocketproxy.go#L166

why not use two `<-errc`

**Comment by fatih** [comment]
Because only one is enough. Once we get one of the copy errors, the rest will fail as well. So having one and printing it is enough for us.

**Comment by cihangir** [comment]
hi @vecio if you have any use case/need for 2 errors, let us know about your situation and feel free to reopen.
